query SubrudditsPosts($limit: Int!, $cursor: String, $subrudditSlug: String) {
	posts(limit: $limit, cursor: $cursor, subrudditSlug: $subrudditSlug) {
		hasMore
		posts {
			...PostSnippetFields
			subruddit {
				id
				name
				description
			}
		}
	}
}
